### PR TITLE
Added Text2Speech in Python

### PR DESCRIPTION
**Pull request by Abtaha**
The program asks what you want to convert to audio. Then it converts the text to audio and plays it

### CODE REVIEW

**Comment by Nikzy7** [comment]
Hey @Abtaha the code that you've written actually prints what the user has spoken. @its-harshil harshil 's problem actually wanted to create a Text To Speech, meaning that the system has to speak (play a sound through the speaker) what the user has entered. Your code is Speech to Text which converts what the user has spoken. The opposite of what was desired. Hope this helps :)

**Comment by Abtaha** [comment]
My bad. Let me fix it

**Comment by Nikzy7** [comment]
Have a look at gTTS 😄

**Comment by Abtaha** [comment]
Changed it. Thanks for the tip!

**Comment by harshilp24** [comment]
@Abtaha thanks for the contribution

**Pull request merged**
