### PR TITLE
Create 404.html

### PR DESCRIPTION
**Pull request by idivyanshbansal**

### CODE REVIEW

**Comment by harshilp24** [comment]
@idivyanshbansal please provide some information regarding the code, like what code does, your little intro etc etc!

**Comment by idivyanshbansal** [comment]
> @idivyanshbansal please provide some information regarding the code, like what code does, your little intro etc etc!

please check out this link to see the working  https://circuitspace.cf/404

**Comment by harshilp24** [comment]
@idivyanshbansal thanks for the link, but please comment some details regarding the code,

What is code about,
What code does,
and your bio

Mention the link inside the code, as it will help other people understand the code.

**Comment by idivyanshbansal** [comment]
> @idivyanshbansal thanks for the link, but please comment some details regarding the code,
> 
> What is code about, What code does, and your bio
> 
> Mention the link inside the code, as it will help other people understand the code.

Is it possible to create a new request for that or can you make me a contributor?
Sir, I have more material to share with you if you like.

**Comment by idivyanshbansal** [comment]
The code is about a fancy 404 page for an HTML website.
The code is made to perform multiple aminations and its animations refer to city, circuit, model, modernization, and many more. 
  
My bio
Divyansh Bansal
idivyanshbansal   https://github.com/idivyanshbansal         https://idivyanshbansal.tk/

**Pull request merged**
