### PR TITLE
Detection of Iris using ML

### PR DESCRIPTION
**Pull request by heyajyoti**
Hands on ML using Pandas,Numpu,Sckit,Matplotlib.

### CODE REVIEW

**Comment by harshilp24** [comment]
@jyotilaxmi98 please commit correct file

**Comment by heyajyoti** [comment]
Can you elaborate what kind of file I need to upload?

**Comment by harshilp24** [comment]
@jyotilaxmi98 check the file you commited, It has some issues, https://github.com/its-harshil/Hacktoberfest_2020/pull/191/files#diff-5ecd7199a3399d3f6f0c5a2e6fb16fb8b794e216ee470942d320987c2bcf84e4

**Comment by heyajyoti** [comment]
okay,I am upoading a new one,kindly check.

**Pull request closed without merging**
